--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lulz/Pictures/wall/Wallpapers/alena_aenami_redskyf.jpg"

-- Special
background="#0f0a17"
foreground="#c3c1c5"
cursor="#c3c1c5"

-- Colors
color0="#0f0a17"
color1="#BB554B"
color2="#E2A055"
color3="#D3B46B"
color4="#2B4C9B"
color5="#2F4E9A"
color6="#566398"
color7="#c3c1c5"
color8="#62596d"
color9="#BB554B"
color10="#E2A055"
color11="#D3B46B"
color12="#2B4C9B"
color13="#2F4E9A"
color14="#566398"
color15="#c3c1c5"
