# Shell variables
# Generated by 'wal'
wallpaper='/home/lulz/Pictures/wall/Wallpapers/guhwm - Default.jpg'

# Special
background='#4a3c33'
foreground='#e5deda'
cursor='#e5deda'

# Colors
color0='#4a3c33'
color1='#B19B8D'
color2='#BBA597'
color3='#C2AC9E'
color4='#CCB6A8'
color5='#D9C5B6'
color6='#E1CCBD'
color7='#e5deda'
color8='#a09b98'
color9='#B19B8D'
color10='#BBA597'
color11='#C2AC9E'
color12='#CCB6A8'
color13='#D9C5B6'
color14='#E1CCBD'
color15='#e5deda'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
