--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lulz/Pictures/wall/Wallpapers/guhwm - Default.jpg"

-- Special
background="#4a3c33"
foreground="#e5deda"
cursor="#e5deda"

-- Colors
color0="#4a3c33"
color1="#B19B8D"
color2="#BBA597"
color3="#C2AC9E"
color4="#CCB6A8"
color5="#D9C5B6"
color6="#E1CCBD"
color7="#e5deda"
color8="#a09b98"
color9="#B19B8D"
color10="#BBA597"
color11="#C2AC9E"
color12="#CCB6A8"
color13="#D9C5B6"
color14="#E1CCBD"
color15="#e5deda"
