#!/bin/bash

#=============================================================================
# guhwm Theme Reveal - First Boot Initialization Script
#=============================================================================
# This script runs ONCE on the first login after installation to create
# a dramatic "theme reveal" experience with smooth wallpaper transitions.
#
# What it does:
#   1. Checks if already run (via flag file)
#   2. Waits for window manager to fully initialize
#   3. Shows "initializing" notification
#   4. Applies wallpaper with smooth transition effect
#   5. Shows "complete" notification
#   6. Creates flag file to never run again
#
# Colors are already pre-generated by guhwizard, so Waybar, Foot, and
# swaync are instantly themed. This script just adds the wallpaper reveal.
#=============================================================================

# Flag file to track if this script has already run
FLAG_FILE="$HOME/.cache/guhwm-theme-revealed"

# Exit immediately if already executed
if [[ -f "$FLAG_FILE" ]]; then
    exit 0
fi

# ============================================================================
# Wait for system to settle (swww daemon needs to be fully initialized)
# ============================================================================
echo "Initializing theme reveal..." >> ~/.cache/theme-reveal.log
sleep 3.0

# Ensure swww-daemon is running
if ! swww query >/dev/null 2>&1; then
    swww-daemon --format xrgb &
    sleep 2.0
fi

# ============================================================================
# Show initialization notification
# ============================================================================
if command -v notify-send >/dev/null 2>&1; then
    notify-send "🎨 guhwm" "Applying Material You theme..." -t 2000 2>/dev/null
fi

# ============================================================================
# Apply wallpaper with DRAMATIC transition effect
# ============================================================================
WALLPAPER="$HOME/.cache/matugen/wallpaper.jpg"

if [[ -f "$WALLPAPER" ]] && command -v swww >/dev/null 2>&1; then
    # Use 'grow' transition for a cinematic reveal effect
    # The wallpaper appears to grow from the center of the screen
    if swww img "$WALLPAPER" \
        --transition-type grow \
        --transition-duration 3 \
        --transition-fps 60 \
        --transition-pos 0.5,0.5 \
        2>&1; then
        
        # Wait for transition to complete before showing success notification
        sleep 3.2
    else
        echo "ERROR: swww failed to apply wallpaper" >> ~/.cache/theme-reveal.log
        notify-send "⚠️ Wallpaper Error" "Failed to apply wallpaper" -t 3000 2>/dev/null
    fi
else
    echo "Warning: Wallpaper not found or swww not available" >> ~/.cache/theme-reveal.log
fi

# ============================================================================
# Show completion notification
# ============================================================================
if command -v notify-send >/dev/null 2>&1; then
    notify-send "✨ Theme Active" "Welcome to guhwm!" -t 3000 2>/dev/null
fi

# ============================================================================
# Create flag file so this only runs once per session
# On next reboot, flag is deleted and script will run again
# ============================================================================
mkdir -p "$(dirname "$FLAG_FILE")"
touch "$FLAG_FILE"

# Note: The flag file prevents multiple runs in same session
# If you want it to never run again, keep the flag file permanent
# Current behavior: runs once on first boot after installation

exit 0
