#!/bin/bash

#=============================================================================
# guhwm Theme Reveal - First Boot Initialization Script
#=============================================================================
# This script runs ONCE on the first login after installation to create
# a dramatic "theme reveal" experience with smooth wallpaper transitions.
#
# What it does:
#   1. Checks if already run (via flag file)
#   2. Waits for window manager to fully initialize
#   3. Shows "initializing" notification
#   4. Applies wallpaper with smooth transition effect
#   5. Shows "complete" notification
#   6. Creates flag file to never run again
#
# Colors are already pre-generated by guhwizard, so Waybar, Foot, and
# swaync are instantly themed. This script just adds the wallpaper reveal.
#=============================================================================

# Flag file to track if this script has already run
FLAG_FILE="$HOME/.cache/guhwm-theme-revealed"

# Exit immediately if already executed
if [[ -f "$FLAG_FILE" ]]; then
    exit 0
fi

# ============================================================================
# Wait for system to settle (swww daemon needs to be fully initialized)
# ============================================================================
sleep 1.5

# ============================================================================
# Show initialization notification
# ============================================================================
if command -v notify-send >/dev/null 2>&1; then
    notify-send "🎨 guhwm" "Applying Material You theme..." -t 2000 2>/dev/null
fi

# Small delay for dramatic effect
sleep 0.5

# ============================================================================
# Apply wallpaper with DRAMATIC transition effect
# ============================================================================
WALLPAPER="$HOME/.cache/matugen/wallpaper.jpg"

if [[ -f "$WALLPAPER" ]] && command -v swww >/dev/null 2>&1; then
    # Use 'grow' transition for a cinematic reveal effect
    # The wallpaper appears to grow from the center of the screen
    swww img "$WALLPAPER" \
        --transition-type grow \
        --transition-duration 3 \
        --transition-fps 60 \
        --transition-pos 0.5,0.5 \
        2>/dev/null
    
    # Wait for transition to complete before showing success notification
    sleep 3.2
else
    echo "Warning: Wallpaper not found or swww not available"
fi

# ============================================================================
# Show completion notification
# ============================================================================
if command -v notify-send >/dev/null 2>&1; then
    notify-send "✨ Theme Active" "Welcome to guhwm!" -t 3000 2>/dev/null
fi

# ============================================================================
# Create flag file so this never runs again
# ============================================================================
mkdir -p "$(dirname "$FLAG_FILE")"
touch "$FLAG_FILE"

# Optional: Could also reload waybar/swaync here if needed
# pkill -SIGUSR2 waybar 2>/dev/null
# swaync-client -rs 2>/dev/null

exit 0
